services:
  # ===== load balancer =====
  haproxy:
    image: haproxy:3.0-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "16M"

  # ===== instancia 1 da api =====
  api1:
    build: .
    image: rinha-fraud:latest
    volumes:
      - sockets:/sockets
    environment:
      - FAISS_NPROBE=${FAISS_NPROBE:-8}
    command: >
      sh -c 'rm -f /sockets/api1.sock &&
      granian --interface asgi
      --uds /sockets/api1.sock --uds-permissions 666
      --workers 1 --runtime-threads 1
      --loop uvloop --backlog 4096
      src.app:app'
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167M"

  # ====== instancia 2 da api =====
  api2:
    build: .
    image: rinha-fraud:latest
    volumes:
      - sockets:/sockets
    environment:
      - FAISS_NPROBE=${FAISS_NPROBE:-8}
    command: >
      sh -c 'rm -f /sockets/api2.sock &&
      granian --interface asgi
      --uds /sockets/api2.sock --uds-permissions 666
      --workers 1 --runtime-threads 1
      --loop uvloop --backlog 4096
      src.app:app'
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167M"

volumes:
  sockets:
